### PR TITLE
Combine aica-docker scripts to one script to avoid symlinks

### PR DESCRIPTION
**Pull request by domire8**
## Description

- #81 

This PR solves the issue by prepending the 'connect', 'interactive', and 'server' scripts as functions to the 'aica-docker' script and then actually copy the latter to `/usr/local/bin`.

## Review guidelines

Estimated Time of Review: 5 minutes

## Checklist before merging:
- [x] Test on NUC (linux)

### CODE REVIEW

**Comment by domire8** [comment]
This does not work on linux..

**Comment by eeberhard** [comment]
Will be glad to test if it works on linux and Mac, and if so it's a nice fix for the issue

**Comment by domire8** [comment]
I've tested this on mac, and on the NUC with two user accounts on linux, should be fine as far as I can tell

**Review by eeberhard — APPROVED** [review]
Tested on my side and works as well, thanks!

**Comment by domire8** [comment]
Could you test again if that fixed your issue?

**Review by eeberhard — APPROVED** [review]

**Pull request merged**
