### PR TITLE
Consolidate images into one single image

### PR DESCRIPTION
**Pull request by domire8**
## Description

- #98 

This PR solves the issue by fast forwarding the commits of the recent PRs to main.

@LouisBrunner if you want to test something with the image, it's already available on my fork (ghcr.io/domire8/ros2-ws:iron).

## Review guidelines

Estimated Time of Review: 3 minutes

## Checklist before merging:

- [x] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

### CODE REVIEW

**Comment by LouisBrunner** [comment]
> @LouisBrunner if you want to test something with the image, it's already available on my fork (ghcr.io/domire8/ros2-ws:iron).

It's amd64 so I can't build another image with it but the metadata looks good

It took much longer to download than the previous ros2-control, any idea why?

**Review by LouisBrunner — APPROVED** [review]

**Comment by domire8** [comment]
> It's amd64 so I can't build another image with it but the metadata looks good

I built multi arch though.

> It took much longer to download than the previous ros2-control, any idea why?

No, I also didn't try to download it to be honest

**Comment by domire8** [comment]
https://github.com/domire8/docker-images/actions/runs/8889677467/job/24408794978

Can you spot a problem here?

The sizes of the images are the same (2.3GB), I dont know why the download takes longer.

**Comment by LouisBrunner** [comment]
> https://github.com/domire8/docker-images/actions/runs/8889677467/job/24408794978
> 
> Can you spot a problem here?

No, it looks good but I still get
```bash
╰─$ docker pull ghcr.io/domire8/ros2-ws:iron
iron: Pulling from domire8/ros2-ws
no matching manifest for linux/arm64/v8 in the manifest list entries
```

> The sizes of the images are the same (2.3GB), I dont know why the download takes longer.

Might just be my connection being slow, no worries then!

**Comment by LouisBrunner** [comment]
Ah, actually

```
        include:
          - image: ubuntu-latest
 ```

You use the same image for both, so they are both `amd64` 😄 
I was confused why the registry was giving a list of 2 different amd64 images in the manifest, that's why

**Comment by domire8** [comment]
Yeah I just figured that out too hehe, mistake when I had to remove the runner that is not configured with my account...All good then I think

**Review by eeberhard — APPROVED** [review]
🔥

**Pull request merged**
